# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 57783ceec053b4265e90f52145037be04ab5f73ab8aae93371aa3579782d751b5e7837eed20a6a3c65f4902a996bb1ed2288a8b8c4d25edd453a089ca52dd0c8

test:
  secret_key_base: e1863d046772d196255d9e1741c67bbf514c803c633b4b16229e5ad39f9b93531085a0e306865834bcb24dbf76de6234c9110f4fb6eb3d06824e5255608480c2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
